name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: yourdockerhubusername/jwtauthdemo
    steps:
      - uses: actions/checkout@v4

      - name: Set environment and version
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          SHORT_SHA=$(git rev-parse --short HEAD)
          if [[ "$BRANCH_NAME" == "main" ]]; then
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
            echo "TAG=prod" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == "develop" ]]; then
            echo "ENVIRONMENT=uat" >> $GITHUB_ENV
            echo "TAG=uat" >> $GITHUB_ENV
          else
            echo "Unsupported branch"
            exit 1
          fi
          echo "VERSION=$SHORT_SHA" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:${{ env.TAG }} .
          docker tag $IMAGE_NAME:${{ env.TAG }} $IMAGE_NAME:${{ env.VERSION }}
          docker tag $IMAGE_NAME:${{ env.TAG }} $IMAGE_NAME:latest

      - name: Push Docker image (version + tag + latest)
        run: |
          docker push $IMAGE_NAME:${{ env.TAG }}
          docker push $IMAGE_NAME:${{ env.VERSION }}
          docker push $IMAGE_NAME:latest
